package MarvelSDK.character.Model;

import lombok.Data;

import java.util.Date;
import java.util.List;

import MarvelSDK.character.MD5Converter;

@Data
public class CharactersRequest {
	private String apiKey;
	private String privateKey;
	private String hash;
	private String tn;
	private String name;
	private String nameStartsWith;
	private Date modifiedSince;
	private List<Integer> comicsIds;
	private List<Integer> seriesIds;
	private List<Integer> eventIds;
	private List<Integer> storyIds;
	private OrderByEnum orderBy;
	private int limit;
	private int offset;

	public String getApiKey() {
		return apiKey;
	}

	public String getHash() {
		return hash;
	}

	public String getName() {
		return name;
	}

	public String getNameStartsWith() {
		return nameStartsWith;
	}

	public Date getModifiedSince() {
		return modifiedSince;
	}

	public List<Integer> getComicsIds() {
		return comicsIds;
	}

	public List<Integer> getSeriesIds() {
		return seriesIds;
	}

	public List<Integer> getEventIds() {
		return eventIds;
	}

	public List<Integer> getStoryIds() {
		return storyIds;
	}

	public OrderByEnum getOrderBy() {
		return orderBy;
	}

	public int getLimit() {
		return limit;
	}

	public int getOffset() {
		return offset;
	}

	public String getTn() {
		return tn;
	}

	// Static Builder class
	public static class Builder {
		private String apiKey;
		private String privateKey;
		private String hash;
		private String tn = String.valueOf(System.currentTimeMillis()); // Generated timestamp
		private String name;
		private String nameStartsWith;
		private Date modifiedSince;
		private List<Integer> comicsIds;
		private List<Integer> seriesIds;
		private List<Integer> eventIds;
		private List<Integer> storyIds;
		private OrderByEnum orderBy;
		private int limit;
		private int offset;

		// Builder constructor
		public Builder(String apiKey, String privateKey) {
			this.apiKey = apiKey;
			this.privateKey = privateKey;
		}

		public Builder hash(String hash) {
			this.hash = hash;
			return this;
		}

		public Builder tn(String tn) {
			this.tn = tn;
			return this;
		}

		public Builder name(String name) {
			this.name = name;
			return this;
		}

		public Builder nameStartsWith(String nameStartsWith) {
			this.nameStartsWith = nameStartsWith;
			return this;
		}

		public Builder modifiedSince(Date modifiedSince) {
			this.modifiedSince = modifiedSince;
			return this;
		}

		public Builder comicsIds(List<Integer> comicsIds) {
			this.comicsIds = comicsIds;
			return this;
		}

		public Builder seriesIds(List<Integer> seriesIds) {
			this.seriesIds = seriesIds;
			return this;
		}

		public Builder eventIds(List<Integer> eventIds) {
			this.eventIds = eventIds;
			return this;
		}

		public Builder storyIds(List<Integer> storyIds) {
			this.storyIds = storyIds;
			return this;
		}

		public Builder orderBy(OrderByEnum orderBy) {
			this.orderBy = orderBy;
			return this;
		}

		public Builder limit(int limit) {
			this.limit = limit;
			return this;
		}

		public Builder offset(int offset) {
			this.offset = offset;
			return this;
		}

		public CharactersRequest build() {
			CharactersRequest request = new CharactersRequest();
			request.apiKey = this.apiKey;
			request.privateKey = this.privateKey;
			// hash is autogenerated
			request.hash =  MD5Converter.generateHash(this.tn + this.privateKey + this.apiKey);
			request.tn = this.tn;
			request.name = this.name;
			request.nameStartsWith = this.nameStartsWith;
			request.modifiedSince = this.modifiedSince;
			request.comicsIds = this.comicsIds;
			request.seriesIds = this.seriesIds;
			request.eventIds = this.eventIds;
			request.storyIds = this.storyIds;
			request.orderBy = this.orderBy;
			request.limit = this.limit;
			request.offset = this.offset;
			return request;
		}
	}

}